name: KM CICD Workflow
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]'

jobs:
    CICD_Workflow:
        runs-on: ubuntu-latest

        steps:
        - name: checkout my source
          id: check_out_mysource
          uses: actions/checkout@v4
        
        - name: trivy scan
          id: trivy_scan
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: fs
            scan-ref: . 
            format: table
            severity: CRITICAL
            output: trivyScan.txt
        
        - name: trivy scan results
          id: trivy_scan_results
          run: |
            trivy_output=$(<trivyScan.txt)
            if echo "$trivy_output" | grep -q "HIGH"; then
              echo "::set-output name=scanFail::true"
            else
              echo "::set-output name=scanFail::false"
            fi
          shell: bash       
                
        - name: Set up QEMU
          if: ${{ steps.trivy_scan_results.outputs.scanFail == 'false' }}
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          if: ${{ steps.trivy_scan_results.outputs.scanFail == 'false' }}
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          if: ${{ steps.trivy_scan_results.outputs.scanFail == 'false' }}
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PW }}
        -
          name: Build and push
          if: ${{ steps.trivy_scan_results.outputs.scanFail == 'false' }}
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: kianmun/go-fortune:${{ github.sha }}
        
               #SLACK_TITTLE: 'Name:'
            #SLACK_MESSAGE: 'Chan Kian Mun'
            #SLACK_TITTLE: 'Matriculation:'
            #SLACK_MESSAGE: 'A0285670W'
            #SLACK_TITTLE: 'Email:'
            #SLACK_MESSAGE: 'e1221482@u.nus.edu'
            #SLACK_TITTLE: 'Git:'
            #SLACK_MESSAGE: 'https://github.com/KianMun/fortune_CICD'
            #SLACK_TITTLE: 'Image:'
            #SLACK_MESSAGE: 'https://hub.docker.com/repository/docker/kianmun/go-fortune/general'
            name: Slack Notification Pass
            id: slack_notification_pass
            if: ${{ steps.trivy_scan_results.outputs.scanFail == 'false' }}
            uses: slackapi/slack-github-action@v1.24.0
            with:
              payload: |
              '{
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "${{ github.repository_owner }}"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Ref:* ${{ github.ref }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Event:* ${{ github.event_name }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Actions URL:* <https://github.com/KianMun/fortune_CICD|KM CICD>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit:* ${{ github.sha }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Image build and signed*\n*Name:* Chan Kian Mun\n*Matriculation:* A0285670W\n*Email:* e1221482@u.nus.edu\n*Git:* https://github.com/KianMun/fortune_CICD\n*Image:* https://hub.docker.com/repository/docker/kianmun/go-fortune/general"
                      }
                    ]
                  }
                ]
              }'          
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST }}
          #env:
            #SLACK_CHANNEL: general
            #SLACK_COLOR: 'good'
            #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
            #SLACK_TITLE: Image Build and signed
            #SLACK_MESSAGE: 
            
              
          
  

        - name: Slack Notification Fail
          id: slack_notification_fail
          if: ${{ steps.trivy_scan_results.outputs.scanFail == 'true' }}
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: general
            SLACK_COLOR: '#FF0000'
            SLACK_MESSAGE: Failed trivy scan, see uploaded report
            SLACK_TITLE: Scan failed
            SLACK_USERNAME: KianMun
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
      
        - name: Upload Trivy Scan
          id: upload_trivy_scan
          if: success()
          uses: adrey/slack-file-upload-action@master
          with:
            token: ${{ secrets.SLACK_TOKEN }}
            path: trivyScan.txt
            channel: test-submission
            title: Scan report by Kian Mun
        

