name: KM CICD Workflow
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]'
    #push:
      #branches:
        #- 'v[0-9]+.[0-9]'

jobs:
    CICD_Workflow:
        runs-on: ubuntu-latest

        steps:
        - name: checkout my source
          id: check_out_mysource
          uses: actions/checkout@v4
        
        - name: scan code for vulnerabilities
          id: scan_code_for_vulnerabilities
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: fs
            scan-ref: . #kianmun/fortunes:latest
            format: table
            severity: CRITICAL, HIGH
            #outfile: scan_results.txt
            output: trivyScan.txt
        
        - name: Slack Notification
          id: slack_notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: general
            SLACK_COLOR: ${{ job.status }} 
            SLACK_MESSAGE: 'Trivy Scan Results:\n ```'${{ steps.scan_code_for_vulnerabilities.outputs.trivyScan }}'```'
            SLACK_TITLE: Trivy Scan Results
            SLACK_USERNAME: KianMun
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
           

#To define scope for to_slack