name: KM CICD Workflow
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]'

jobs:
    CICD_Workflow:
        runs-on: ubuntu-latest

        steps:
        - name: checkout my source
          id: check_out_mysource
          uses: actions/checkout@v4
        
        - name: trivy scan
          id: trivy_scan
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: fs
            scan-ref: . 
            format: table
            severity: CRITICAL
            output: trivyScan.txt
        
        - name: trivy scan results
          id: trivy_scan_results
          run: |
            trivy_output=$(<trivyScan.txt)
            if echo "$trivy_output" | grep -q "HIGH"; then
              echo "::set-output name=scanFail::true"
            else
              echo "::set-output name=scanFail::false"
            fi
          shell: bash
        
        - name: Slack Notification Fail
          id: slack_notification_fail
          if: ${{ steps.trivy_scan_results.outputs.scanFail == 'true' }}
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: general
            SLACK_COLOR: '#FF0000'
            SLACK_MESSAGE: Failed trivy scan, see uploaded report
            SLACK_TITLE: Scan failed
            SLACK_USERNAME: KianMun
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
        
        - name: Upload Trivy Scan
          id: upload_trivy_scan
          if: success()
          uses: adrey/slack-file-upload-action@master
          with:
            token: ${{ secrets.SLACK_TOKEN }}
            path: trivyScan.txt
            channel: test-submission
            title: Scan report by Kian Mun
        
        - name: Set up QEMU
          if: failure()
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          if: success()
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          if: success()
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PW }}
        -
          name: Build and push
          if: success()
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: user/app:latest
        
        - name: Slack Notification Pass
          id: slack_notification_pass
          if: success()
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: general
            SLACK_COLOR: 'good'
            SLACK_TITLE: Image build and signed
            SLACK_MESSAGE: 'Name: Chan Kian Mun' 
            #SLACK_MESSAGE: 'Matriculation: A0285670W'
            #SLACK_MESSAGE: 'Email: e1221482@u.nus.edu'
            #SLACK_MESSAGE: 'Git: https://github.com/KianMun/fortune_CICD'
            SLACK_USERNAME: KianMun
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
        

