name: KM CICD Workflow
on:
- push
    #push:
      #branches:
        #- 'v[0-9]+.[0-9]'

jobs:
    CICD_Workflow:
        runs-on: ubuntu-latest

        steps:
        - name: checkout my source
          id: check_out_mysource
          uses: actions/checkout@v4
        
        - name: scan code for vulnerabilities
          id: scan_code_for_vulnerabilities
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: kianmun/fortunes:latest
            format: table
            severity: CRITICAL, HIGH
            outfile: scan_results.txt
        
        - name: Send to Slack
          id: to_slack
          uses: slackapi/slack-github-action@v1.24.0
          with:
            #channel-id: "test-submission"
            #slack-message: "Testing the test of all tests"
            payload: |
              {
                
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Name: Chan Kian Mun"
                    }
                  }
                ]
              }
            payload-file-path: scan_results.txt
          env: 
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST }}
            #SLACK_BODY: ${{ steps.scan_code_for_vulnerabilities.outputs.scan-result }}
            #SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
           

#To define scope for to_slack