name: KM CICD Workflow
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]'

jobs:
    CICD_Workflow:
        runs-on: ubuntu-latest

        steps:
        - name: checkout my source
          id: check_out_mysource
          uses: actions/checkout@v4
        
        - name: trivy scan
          id: trivy_scan
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: fs
            scan-ref: . #kianmun/fortunes:latest
            format: table
            severity: HIGH
            output: trivyScan.txt
        
        - name: trivy scan results
          id: trivy_scan_results
          run: |
            trivy_output=$(<trivyScan.txt)
            if echo "$trivy_output" | grep -q "HIGH"; then
              echo "::set-output name=found_high_severity_vulnerabilities::true"
            else
              echo "::set-output name=found_high_severity_vulnerabilities::false"
            fi
          shell: bash
        
        - name: Slack Notification Fail
          id: slack_notification_fail
          if: ${{ steps.trivy_scan_results.outputs.found_high_severity_vulnerabilities == 'true' }}
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: general
            SLACK_COLOR: ${{ job.status }} 
            SLACK_MESSAGE: Scan Failed
            SLACK_TITLE: Scan Results
            SLACK_USERNAME: KianMun
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
        
 
        - name: Upload Trivy Scan
          if: success()
          uses: MeilCli/slack-upload-file@v3
          with:
            content: 'file content'
            file_name: 'trivyScan.txt'
            title: 'trivyScan'
            slack_token: ${{ secrets.SLACK_TOKEN }}
           

#To define scope for to_slack